### ISSUE TITLE
launch error

### ISSUE THREAD

**Issue by weboid123** [vagabondHustler/subsearch#240]
when I run executable, I get this error:
Traceback (most recent call last):
File "subsearch\__main__.py ", line 3, in <module>
File "subsearch\__init__.py ", line 114, in main
File "subsearch\__init__.py ", line 19, in __init__
File "subsearch\__subsearch__.py ", line 82, in __init__
File "subsearch\utils\raw_registry.py ", line 131, in add_context_menu
File "subsearch\utils\raw_registry.py ", line 20, in write_keys
FileNotFoundError: [WinError 2] The specified file cannot be found

**Comment by vagabondHustler** [comment]
Which version of windows are you on?

If you run the registry editor (win+r, regedit enter), do you have this path Computer\HKEY_CURRENT_USER\Software\Classes\*

**Comment by weboid123** [comment]
> Which version of windows are you on?
> 
> If you run the registry editor (win+r, regedit enter), do you have this path Computer\HKEY_CURRENT_USER\Software\Classes*

v2.24.2

**Comment by weboid123** [comment]
> Which version of windows are you on?
> 
win 8.1 xd

> If you run the registry editor (win+r, regedit enter), do you have this path Computer\HKEY_CURRENT_USER\Software\Classes*
yez

**Comment by vagabondHustler** [comment]
> > Which version of windows are you on?
> 
> win 8.1 xd
> 
> > If you run the registry editor (win+r, regedit enter), do you have this path Computer\HKEY_CURRENT_USER\Software\Classes*
> 
> yez

Okay, I'm unsure why this happens if you have that path. I'm gonna look into it and get back to you :)

**Comment by vagabondHustler** [comment]
Okay, fired up a win 8.1 x64 VM and think i found the problem. Gonna build a new .exe soon. In the meanwhile you can always do this.

Run the registry editor (WIN + R > regedit > ok)
go to `Computer\HKEY_CURRENT_USER\Software\Classes\`
right click on the folder/key named `Classes` new > key
and name it *
and run subsearch.exe

![Screenshot 2022-09-21 140046](https://user-images.githubusercontent.com/92130287/191498554-71793b5d-feaa-4f2b-b751-a59b6fdf5e7c.png)

**Comment by weboid123** [comment]
tysm m8!

**Comment by vagabondHustler** [comment]
> tysm m8!

No problem. v2.24.3 should be out in a few minutes.
