### ISSUE TITLE
[BUG] FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mertc\\AppData\\Local\\Subsearch\\config.toml'

### ISSUE THREAD

**Issue by cobanov** [vagabondHustler/subsearch#510]
```
Traceback (most recent call last):
  File "C:\Users\mertc\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mertc\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\mertc\miniconda3\Scripts\subsearch.exe\__main__.py", line 7, in <module>
  File "C:\Users\mertc\miniconda3\lib\site-packages\subsearch\utils\decorators.py", line 31, in inner
    return func(*args, **kwargs)
  File "C:\Users\mertc\miniconda3\lib\site-packages\subsearch\__init__.py", line 65, in main
    app = Subsearch()
  File "C:\Users\mertc\miniconda3\lib\site-packages\subsearch\__init__.py", line 20, in __init__
    self.subsearch_core = core.SubsearchCore(PREF_COUNTER)
  File "C:\Users\mertc\miniconda3\lib\site-packages\subsearch\core.py", line 85, in __init__
    Initializer.__init__(self, pref_counter)
  File "C:\Users\mertc\miniconda3\lib\site-packages\subsearch\core.py", line 23, in __init__
    self.setup_file_system()
  File "C:\Users\mertc\miniconda3\lib\site-packages\subsearch\core.py", line 65, in setup_file_system
    io_toml.resolve_on_integrity_failure()
  File "C:\Users\mertc\miniconda3\lib\site-packages\subsearch\utils\io_toml.py", line 77, in resolve_on_integrity_failure
    dump_toml_data(FILE_PATHS.config, DEFAULT_CONFIG)
  File "C:\Users\mertc\miniconda3\lib\site-packages\subsearch\utils\io_toml.py", line 24, in dump_toml_data
    with open(toml_file_path, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mertc\\AppData\\Local\\Subsearch\\config.toml'
```

**Comment by vagabondHustler** [comment]
See if [2.39.1](https://github.com/vagabondHustler/subsearch/releases/tag/v2.39.1) fixes the issue, when it's finished building. Otherwise i need some more info to go on so I can reproduce the problem.

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. window 10]
 - Python version [e.g python311]
 - Ran from [e.g source, pypi]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
```

**Comment by vagabondHustler** [comment]
See if [2.39.2](https://github.com/vagabondHustler/subsearch/releases/tag/v2.39.2) fixes the issue, when it's finished building. Otherwise i need some more info to go on so I can reproduce the problem.

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. window 10]
 - Python version [e.g python311]
 - Ran from [e.g source, pypi]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
```
